apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docs
  labels:
    app: docs
spec:
  replicas: {{ .Values.docs.replicas }}
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag }}"
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - containerPort: 80