[workspace]
authors = ["{{ author }}"]
channels = ["conda-forge"]
name = "{{ project-name }}"
platforms = [
    "{{ platform }}"
]
version = "{{ project-version }}"
readme = "README.md"

[workspace.dependencies]
rust = "*"
mojo = "*"

[dependencies]

[environments]